import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from './StoreProvider'
import { createClient } from '@/utils/supabase/server'
import { ThemeProvider } from '@/components/theme-provider'
import { ClientLoginDispatch } from '@/components/client-login-dispatch'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <StoreProvider>
            <ClientLoginDispatch user={user}>{children}</ClientLoginDispatch>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
